### ISSUE TITLE
Scos System Test for Local Platform Chart

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/smartcitiesdata#109]
As a developer implementing the Smart Cities data platform, I want an easy way to run the entire system on my machine.

Acceptance Criteria:
* All apps can be deployed locally using a single chart
* Scos system tests runs locally
* Include all dependent services as dependent charts

**Comment by ManApart** [comment]
This was born from the fires of smartcitiesdata#38 and is a 'put a bow on it' card.

**Comment by jdenen** [comment]
> As a developer implementing the Smart Cities data platform, I want an easy way to run the entire system on my machine.

Closing because of the umbrella. While the umbrella work is not complete quite yet, this doesn't feel like a useful issue anymore. Feel free to re-open if you disagree @ManApart @jeffgrunewald

**Comment by jeffgrunewald** [comment]
Agreed. As long as standing up a compose stack for non-BEAM components, including Orcimer and other pipeline-internal components not written in elixir I don’t think the JSR is there anymore.
