### ISSUE TITLE
CVE - Kapsch push gateway (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#126]
So hyuge and undefined, it gets TWO XXL placeholders for now

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS

**Comment by rob-h-m** [comment]
Reducing the Kapsch gateway portion to a placeholder of 21 based on discussion 12/3/19

**Comment by rob-h-m** [comment]
Cards have been written, closing
