### ISSUE TITLE
Travis builds should stop when an error or failure is encountered

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/smartcitiesdata#134]
Travis builds should stop whenever they encounter a failure instead of running till completion and then failing. This wastes compute time (which is free) as well as developer time (which is not free).

As a developer or contributer I want to know that my code has failed immediately, without having to wait an additional 5-10 minutes.

AC:
- Travis fails as soon as it encounters an error (like a failed test)
- Complete this on a single repo with a lot of tests such as discovery-api

TN:
- The best way to do this is probably by running travis builds in stages. This should give us the acceptance criteria as well as a logical grouping of the different steps of travis.
- `set -e` is another option; it should cause the build to fail anytime a command returns a non-zero exit code.

**Comment by rob-h-m** [comment]
@jeffgrunewald Double check on this one

**Comment by ManApart** [comment]
I think Jarred has played this with a single repo.

**Comment by rob-h-m** [comment]
@JarredOlson What is the JSR on this one?
