### ISSUE TITLE
Easy Mile Autonomous Shuttle (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#140]
Wild Guess placeholder to update the burn up - NEEDS UPDATED ONCE WE UNDERSTAND THE SCOPE OF THE REQUIREMENTS BETTER

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS

**Comment by rob-h-m** [comment]
From discussion on 12/2, reducing the size of this placeholder from 21 to 5.

**Comment by rob-h-m** [comment]
Closing, cards have been refined for this
