### ISSUE TITLE
Mid-Ohio Foodbank Data Ingestion (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#141]
Placeholder for work to consume data from Hands On (based on Jeff's estimate of a dev pair for two sprints)

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS

**Comment by rob-h-m** [comment]
Reducing the placeholder based on discussion on 12/2/19

**Comment by rob-h-m** [comment]
Reducing further from 5 to 3
