### ISSUE TITLE
Andi downcases column names

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#147]
From smartcitiesdata/andi 56
Per @rajones-hntb 

When presented a dataset definition containing a schema, andi should downcase the column names to ensure a proper match when compared to results from Presto.

AC:
- Andi downcases names in the schema

TN: 

- Make sure that the schema will work with forklift, reaper, valkyrie, and flair

**Comment by sukaant** [comment]
Using this bad boi as a test case
Ohio Worker Classification - Census Tract 2006 - 2010 -- Total Workers (Workers 16 years and over)

https://discovery.dev.internal.smartcolumbusos.com/dataset/aashto/15c31c63_151a_4f6d_97e3_2a2d97621a4c

**Comment by ManApart** [comment]
The migration of existing dataset definitions will take place in https://github.com/smartcitiesdata/smartcitiesdata/issues/238
