### ISSUE TITLE
Andi: Delete Dataset API

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#148]
From smartcitiesdata/andi 57
Per @abrock-accenture  

As a system administrator
I want the ability to easily remove a dataset and all associated data from the system
So that I can know with confidence that it has been cleaned up

ACs:

- Some programmatic interface that can remove a dataset in a single call

Tech Notes:

- Assuming this will utilize Brook and the event stream

Things that we currently have to deal with:

  * Kafka Topics
  * Redis Keys
  * Brook View states
  * Reaper Supervisors
  * Presto Tables

**Comment by jmorris-pillar** [comment]
Notes from most recent meeting:

Andi can fire an event which deletes a dataset

When this event is fired the following will occur
AC:
    - Reaper stops ingesting the dataset
    - Topics are deleted or their consumer groups are reset to HEAD
    - Data is not reingested or app restart unless triggered by a dataset update/ingest event.
    - The dataset can be reingested as if it had never been in the system.
    - The dataset is not displayed on discovery-ui / discovery-api
    - The data is deleted from presto

**Comment by jakeprem** [comment]
This should also clean up secrets and credentials

**Comment by jakeprem** [comment]
ACs for future cards:

General
---
  * Dataset can be reingested as if it had never been in the system
  * Topics are cleaned up - either deleted or consumer groups are reset to HEAD

Reaper
---
  * Reaper stops ingesting dataset
  * Reaper removes dataset from its Brook view state
  * Reaper does not reingest dataset when it restarts (unless a new event for the dataset is posted)

Voltron
---
  * Voltron deletes dataset from its view state

Forklift
---
  * Forklift deletes table and data
  * Forklift deletes dataset from its view state

Discovery API
---
  * Discovery API deletes dataset from its view state

Andi
---
  * Andi deletes dataset from its view state
