### ISSUE TITLE
Store a limited amount of events in redis for a brook viewstate

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#153]
As a system administrator, I want to ensure Redis does not get overfull by events in that fire in often in the system.

AC:

- Provide an ability to limit the amount of events for any event type as a brook configuration.
- When this is configured, event logs in redis are truncated automatically to fit inside these limits.

Technical notes:
- Redis storage of brook events are segmented by type.

**Comment by rob-h-m** [comment]
@bbalser And one more - is this in progress?  Thank you
