### ISSUE TITLE
Improve encoding of brook events

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#154]
Currently there are some difficulties with the way we are doing term to bin for brook events which cause these to sometimes end up in a bad state (talk to brian about this)

The proposed solution is to first encode these events into json before performing term to bin or storing them as json.  (This can be decided on grooming)

**Comment by rob-h-m** [comment]
@bbalser   Our (Carrie,  Jeff, me) suspicion is that you are already working on this?  Thanks
