### ISSUE TITLE
Allow brook to be instantiated multiple times in one application and invoked by name

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#155]
We have identified a need to be able to operate on a named instance of brook rather than brook being treated as a singleton within an application.

E.g. Brook.get_all(:some_brook, some_collection)

This should improve usability inside of the umbrella effort

**Comment by rob-h-m** [comment]
@balser Ditto - are you already working on this one? Thanks
