### ISSUE TITLE
Set object expiration for versions of compacted data

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/smartcitiesdata#165]
@rajones-hntb commented on [Mon Sep 16 2019](https://github.com/smartcitiesdata/forklift/issues/100)

Presto S3 bucket has versioning enabled. We do not want to retain these previous version indefinitely.

AC:
Apply a TTL for objects stored in the presto-hive s3 buckets. 

Tech Note:
If this requires recreating the bucket, have a separate conversation about how to do that in a sane way/doing it in general.

**Comment by JarredOlson** [comment]
Buckets were already setup with versioning disabled so there is nothing to do here.
