### ISSUE TITLE
Unpack ARCGIS - DoIM Dashboard (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#177]
Placeholder

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS

**Comment by rob-h-m** [comment]
Splitting agency pilot dashboard into two epics

**Comment by rob-h-m** [comment]
Reduced to reflect cards written
