### ISSUE TITLE
RFC: App specific tagging

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/smartcitiesdata#192]
### Background
Versioning individual applications inside the umbrella seems like what we want right now. It gives us the most flexibility and keeps aligned with how Columbus uses the platform. 

### Now
To release any application in the umbrella, I tag the platform. The build script moves through `apps/` subdirectories containing Dockerfiles, builds them, and publishes. Any app that hasn't changed should see no new images in DockerHub since the cached layer hasn't changed.

### Issue
If I make a change for one app that affects another -- but not in a meaningful way -- I have to rev versions for both and publish both. In the multi-repository model, I wouldn't have to do that. In fact, I probably wouldn't have updated the other app in the first place.

Best example here is how I just updated Brook. It went from `v0.4.1` to `v0.4.3`. I needed this as part of Forklift. Don't need it in Andi. I'm going to have to rev both and release both. Andi's functionality/behavior was not changed in any way. Just the dependency changed (with no benefit to Andi).

### Proposal
I propose we make application specific tags against the umbrella repo and release based on those tags. The `development` tag process should not be changed.

Using the same Brook example from above: I would change Forklift's version to `0.8.3` and tag this repo with `forklift:0.8.3`. A new forklift image would be published to DockerHub. 

Nothing would happen to Andi.

**Comment by NathanielScottStevens** [comment]
This makes sense to me. Would we still be specifying the version we want deployed in a deploy repo?

**Comment by jdenen** [comment]
Yeah, deployment processes are up to the teams who own the environment(s). This is about how we publish images from the general platform and not specific to any users of the platform.

(I'm trying to think impartially as opposed to think about this as a member of the Columbus team.)

**Comment by jmorris-pillar** [comment]
Does this mean that future builds of andi in your example would possibly have hidden bugs? Whenever another more deliberate change is made to andi, and it release with some Brook x+1, would this cause confusion/problems?

**Comment by jdenen** [comment]
I don't _think_ so. It's not like integration/e2e tests don't have to pass for andi. It's just that we have no real reason to publish andi's image.

**Comment by jmorris-pillar** [comment]
So integration tests for individual apps have to pass.  Is it possible there are bugs which are not captured by those tests though?  I'm not saying this is a strong reason to /not/ do this, but it should be considered it basically breaks the idea of continuous delivery in that an application is being changed and you sit on the changes.

**Comment by jdenen** [comment]
The general platform has nowhere to continuously deliver to, except DockerHub. With that in mind, I'd rather consciously make the decision to push changes to one app to DockerHub than possibly (and accidentally) push changes to multiple unintended apps.

**Comment by jmorris-pillar** [comment]
Lets replace continuous deployment with timely deployment.  Sometimes a part of the platform can stagnate for weeks to a month.  If an app has had 2,3,4,5 dependencies change and yet has not been deployed to production in a month, is there a way to both have the ability to not /have/ to deploy it, but to be notified that maybe it would be /proactive/ to do so?

**Comment by jmorris-pillar** [comment]
Further, the E2E tests are running predicated on this updated app being part of the e2e, yet it is not tagged, bagged, and deployed.  So we are using our judgement to decide whether or not the e2e tests are actually providing a positive result to a piecemeal deployment being safe.

i.e.  I update brook which forklift consumes.  In the umbrella app, I run the e2e tests, these are ran in the context of andi having the newest brook.  I deploy forklift to production and now since andi isnt using the newest brook shiny, we got a false pass from e2e that leads to a surprisingly broken production.

**Comment by jdenen** [comment]
> Lets replace continuous deployment with timely deployment.

> yet has not been deployed to production in a month

There is no production for the general platform. I can't stress this point enough. 

How Columbus pulls in general platform artifacts and deploys them to dev/staging/production is up to Columbus. 

I recognize this is weird considering the general platform and Columbus has been synonymous for so long, but I have to start pushing this issue. It can't remain synonymous if the general platform is going to grow.

> I update brook which forklift consumes. In the umbrella app, I run the e2e tests, these are ran in the context of andi having the newest brook. I deploy forklift to production and now since andi isnt using the newest brook shiny, we got a false pass from e2e that leads to a surprisingly broken production.

1. Columbus has a staging environment. It should be used like one instead of a glorified dev environment.
2. This requires being able to run e2e tests against an environment (staging), which I'm going to make happen. I admit that this is probably noteworthy context that I left out. :manbun:

**Comment by jdenen** [comment]
Other context that I've left out:

In addition to this type of service releases, we'll need to release platform-point-in-time via an uber chart. And I imagine we'll do things to encourage platform users to upgrade the platform instead of individual components.

**Comment by jdenen** [comment]
This has been implemented.
