### ISSUE TITLE
Persist event stream events

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#200]
As a developer
I want to be able to access historical event stream events
So that I have a record for trouble shooting and other functions

AC:
- event stream events are persisted into a long-term storage solution

TN:
- Store in Presto (using forklift style inserts and not the new orc -> s3 approach)
- Create a new microservice to connect to Presto rather than using the Kafka Presto Connector
- In the Umbrella

**Comment by jeffgrunewald** [comment]
What is the alternative to doing that approach? I thought it was pretty well decided we needed a new app that read and wrote directly to presto like flair does

**Comment by jdenen** [comment]
Yeah this should be a new microservice. Like @jeffgrunewald says, there's not really a better option. There's probably some complicated stuff we could do with the Kafka Presto connector, but it doesn't seem worth it at all.

**Comment by rob-h-m** [comment]
Based on the discussion above, moving this to Ready to Refine
