### ISSUE TITLE
SPIKE: Better key management and a way to roll keys

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#212]
#### Acceptance Criteria: 

- [ ] Research way(s) to better manage the K8 keys (kube configs, ssh keys to eks nodes) within our system 
- [ ] Research way(s) to roll keys.  How can we change our kube configs and eks keys safely when people leave the team?
- [ ] Discuss recommendations with @jmorris-pillar 
- [ ] Write dev cards which allow us to implement any key rolling/management solutions.

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should move to SmartColumbusOS
