### ISSUE TITLE
SPIKE: Can we put the K8 control plane inside of the VPN?

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#213]
Currently the EKS master nodes and the ability to talk to them via kubectl and the http api is exposed to the internet and can be accessed by anyone who is able to obtain a kubeconfig and an aws token.  We could have better security for managing the cluster if the master nodes // control plane were inside of the VPN.  

Is this possible?  

What are the downsides?

#### Acceptance Criteria: 

- [ ] Answer the title question 
- [ ] Review findings with @jmorris-pillar to determine path forward
- [ ] Write dev card(s) if applicable

**Comment by jdenen** [comment]
@rob-h-m 
This is specific to Columbus and should be moved to SmartColumbusOS
