### ISSUE TITLE
SPIKE: Can we have a K8 audit trail of what happened and who did it?

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#214]
We perform kubernetes changes using our aws credentials (via heptio), yet we are either not tracking who performs what actions, or we have not become aware of where this is tracked.

#### Acceptance Criteria: 

- [ ] Is it possible to log who performed what actions in a kubernetes cluster?
- [ ] How could we get back to this information
- [ ] Could we export this somewhere which is indexible like Kibana?
- [ ] Discuss findings with @jmorris-pillar to determine approach forward 
- [ ] Write dev card(s)

**Comment by jdenen** [comment]
This is a SmartColumbusOS issue, not a general platform issue.
