### ISSUE TITLE
Andi: Status page displays list of datasets

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#218]
#### Acceptance Criteria: 

- [ ] There is a list of all datasets on the page including dataset name and date modified
- [ ] @jakeclark to provide comps/input on column headers, etc.
- [ ] Handle no data, error, and loading 

#### Amigos: 

@jakeclark, @NathanielScottStevens, @jakeprem 

#### Tech Notes: 

- This will be done as an effort to validate that Phoenix will work going forward
- Datasets as links is out of scope
- Make sure the browser pipeline is correct

**Comment by jakeprem** [comment]
##### Questions for entry:

  * What is the date modified we want to be using here? As far as I can see, we only have modifiedDate currently, which should be the last date the dataset was modified (by the source?) not the last time it was modified in our system.
