### ISSUE TITLE
Add status indicator

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#221]
_As a data curator, I want to know which datasets are still being curated, so I can focus on them._

#### Acceptance Criteria: 

- [ ] Status' below are show in the status column in the table:
- Where data definition is not completed (Status: "Unexecuted Data Definition")
- Ingested (Status: "Ingested")
- [ ] Status' are sortable by ingested or not ingested

#### Amigos: 

@jakeclark , @NathanielScottStevens, @ramboyapati 

#### Tech Notes: 

- This is focused on the one-time ingestion datasets 
- Upon entry, determine which event this is going to key off of

**Comment by ramboyapati** [comment]
It would be helpful to have one more distinction.
1. Where data definition is not completed (Status: "Data Definition")
2. Data definition completed. Ingestion in progress (Status: "Ingestion In Progress")
3. Ingested (Status: "Ingested")

Thoughts? @carriebrinkley @NathanielScottStevens

**Comment by ManApart** [comment]
@ramboyapati 1 and 3 make sense. Unfortunatly we don't currently have a good way of determining 2, though hopefully we will in time.

**Comment by NathanielScottStevens** [comment]
@ramboyapati I would have to know more about what you mean by "data definition is not completed". My interpretation is that this means the user has drafted a data definition but has not executed it yet. At the time of playing this card we won't have a way of drafting a dataset so the status would be meaningless (Although this could be useful once that draft feature is in place). Let me know your thoughts.

@ManApart I see 2 as determinable by using the Ingest Start event. Are we interpreting the status differently?

**Comment by carriebrinkley** [comment]
@NathanielScottStevens @ramboyapati @ManApart I am interpreting them as follows: 

1. Data definition is not completed - the ingest has failed for some reason 
2. Ingestion in progress - triggered by ingest start event.  Status is persisted until either 1 or 3 (below) occurs
3. Ingested - it is successfully in the system

**Comment by ManApart** [comment]
That makes sense. I don't know why I didn't think of just using the ingest start event.

**Comment by ramboyapati** [comment]
@NathanielScottStevens @carriebrinkley @ManApart 
#1 I wrote the card with the intention of having the ability to save the progress of data defined as a draft. 
For our initial pass, are we only updating the data dictionary all at once? If this is the case, I agree that data definition not complete status is not required.

In this case, 1. ingestion in progress, 2. ingestion failed, and 3. ingestion success could be the status indicators. All three statuses are telling that the data definition part is complete. _(the assumption is that we are able to validate the data definition and are sure that it is 100% complete)._

What are the chances that the data ingestion will fail as a result of errors in data definition? From what I gathered, we will have a test feature that validates API. Batch data will be uploaded to S3. 
If there is a scenario where ingestion failed as a result of inaccurate data definition, then we would be modifying the data definition. 

Let me know your thoughts?

**Comment by NathanielScottStevens** [comment]
We are intending to be able to save a draft of the dataset definition but that work will come later on down the road.

We would also like to display ingestion failure as a status but don't have a good way of doing that at the moment. But we definitely intend to have that as a status in the future!

**Comment by ManApart** [comment]
`defmacro data_ingest_end(), do: quote(do: "data:ingest:end")`

**Comment by ManApart** [comment]
Column to the left of organization
-named: Ingested
-ingested datasets -> green checkmark
-not ingested datasets -> empty / nothing
