### ISSUE TITLE
Forklift buffers data to mongo before inserting it into presto

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#226]
_As a data curator, I want to be able to ingest large datasets quickly so that they can provide value to the public with a quick turnaround._

### Acceptance Criteria
- [ ] On dataset:update, create a new table in mongo for the dataset
- [ ] As data flows into forklift, it is first persisted into the above mongo table with a transaction id and partitionID as a keys
- [ ] If mongo is inaccessible forklift inserts this data directly into presto
- [ ] On EOF or configurable N messages consumed (for a transaction) Forklift will use the presto connector of mongo to insert data from mongo into presto, deleting the old data from mongo as it succeeds
- [ ] The last completed Transaction ID's are stored in an association table with their dataset:partition tuple so they can be referenced on restart

### Tech Notes
- This should limit the need for compaction on new datasets as this will perform the same operation since all data will be first inserted into mongo.
- This card is attempting to make it possible for forklift to handle multiple partitions
- When writes to mongo are unsuccessful, do exponential backoff and do not consume messages from kafka

**Comment by jeffgrunewald** [comment]
Going in a different direction.
