### ISSUE TITLE
Forklift flushes data persisted to mongo to presto on startup before ingesting more data 

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#230]
_As a data curator, I want to be able to ingest large datasets quickly so that they can provide value to the public with a quick turnaround._

### Acceptance Criteria
- [ ] On startup, forklift inserts all data into presto that exists in mongo before ingesting new data for all datasets
- [ ] As per in standard processing, when this is complete the transaction:partition:dataset table in presto is updated and the rows are deleted from mongo

**Comment by jeffgrunewald** [comment]
Going in a different direction.
