### ISSUE TITLE
Search type ahead 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#234]
_As a data curator, I want it to be easy to find datasets, so that I can work faster._

#### Acceptance Criteria: 

- [ ] Datasets automatically filter based on the words typed into the search bar on the dataset status page 

#### Amigos: 

@jakeclark , @NathanielScottStevens

**Comment by abrock-accenture** [comment]
@carriebrinkley @NathanielScottStevens Do we have a card to set up the pagination feature on this page?  There will be interplay between our filter/search functionality that we will want to consider.

**Comment by rob-h-m** [comment]
Delivered as part of #219

**Comment by NathanielScottStevens** [comment]
@abrock-accenture I don't believe that card has been created yet.
