### ISSUE TITLE
SPIKE: Making Pivot's Shared Streets dashboard available in the OS

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#235]
#### Background:

As a part of our partnership with Pivot, we would like to make their Shared Streets dashboard available from the OS.  

The dashboard can be found here:

https://mmapi.etch.app/metrics/

The open source Shared Streets code can be found here: 

https://github.com/sharedstreets/mobility-metrics

#### Questions to answer: 

- What options do we have for making the dashboard available through the OS?  
- What level of effort is associated with each of these options? 
- What does it look like to maintain/support each of these options? 

#### Acceptance Criteria: 

- [ ] Answer the above questions
- [ ] Present options to @carriebrinkley , @jakeclark , and @JarredOlson to make an implementation decision 
- [ ] Work with @carriebrinkley to write the dev card(s)

**Comment by jdenen** [comment]
Is the goal of this work for Pivot to stop hosting the visualization and for SMRT to start hosting it? Or is the goal to recreate the dashboard inside the data platform?

If the former, this is a SmartColumbusOS issue. If the latter, this should be done in a generic, not-specific-to-pivot way.

**Comment by jeffgrunewald** [comment]
Agreed. This is Columbus specific as currently written. Perhaps the spike can focus on a plugin system for embedding arbitrary vendor-provided dashboards fed from the system data into the general platform.
