### ISSUE TITLE
Standup Sandbox Environment for Pen Testing

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#237]
We need to stand up a sandbox environment for pen testing.  This also fits in with the dev team's desire to be able to create a performance test environment on demand.

### AC:
- [x] Sandbox environment running
- [x] Something on the cluster is reachable on public DNS
- [x] Tearing Down removes all resources.

### Tech note:
- #239 was split off from this during refinement

**Comment by rob-h-m** [comment]
If anything learned from this card helps with common #432 or common #433 - please update those cards to capture it.  Thanks
