### ISSUE TITLE
Migrate existing datasets to datasets with lowercase column names

### ISSUE THREAD

**Issue by sukaant** [smartcitiesdata/smartcitiesdata#238]
When presented a dataset definition containing a schema, andi should downcase the column names to ensure a proper match when compared to results from Presto.

AC:
- Existing datasets are migrated to have all lower case column names
- Migration should not require a manual step that users must remember to do; this should be done as part of an app's startup

Tech Notes:

This was spun off of https://github.com/smartcitiesdata/smartcitiesdata/issues/147

**Comment by ManApart** [comment]
Closing this as we've (@jeffgrunewald @jmorris-pillar ) decided to not downcase columns and just leave them inconsistent in the system (due to lack of business value).
