### ISSUE TITLE
Migrate existing datasets to have valid ISO8601 datetimes

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#242]
As a data consumer, I want to be able to sort by the dataset modified date and be confident that datasets are sorted accurately.  

Some datasets in the system in the various environments have bad modifiedDates which do not sort or parse properly.  Please migrate the datasets in the system to have the appropriate modifiedDate formats

AC:
[ ] - All modifiedDates are validated and modified to be valid to the best of our ability (e.g. turn 11/11/2019 into 2019-11-11T00:00:00Z)
[ ] - Datasets on discovery-ui sort appropriately when sort by -> modified date is selected.
[ ] - Datasets which cannot have their modified dates resolved are set to modifiedDate = "" and these are sorted last

**Comment by ManApart** [comment]
` Datasets which cannot have their modified dates resolved are set to modifiedDate = "" and these are sorted last`
Are these ALREADY sorted last?
