### ISSUE TITLE
Setup Joomla in Sandbox Environment for Pen Testing

### ISSUE THREAD

**Issue by LtChae** [smartcitiesdata/smartcitiesdata#246]
Pending input from Warner, we need to have Joomla added to our pen testing environment in sandbox.

### AC:
- [ ] Joomla is reachable on public DNS
- [ ] Link from discovery.pen-test.sandbox.internal.smartcolumbusos.com reaches it
- [ ] mailers and forms are configured to not send to prod addresses or disabled or set to a special address

### Tech note:
- Joomla requires its RDS to be deployed via common and then its deployed docker must have akeeba backup restored from prod and hacked to point at that RDS. Alternatively, y'all could start from scratch with it.
- See https://github.com/SmartColumbusOS/pen-test-deploy for details on how the pen test environment is currently set up.
- NOTE: pen testing environment is currently scaled down via its ASG, you will need to scale it back up to ![image](https://user-images.githubusercontent.com/5122881/67975167-fe112900-fbe9-11e9-8025-d174518eb7b6.png)

**Comment by jdenen** [comment]
This issue should be moved to SmartColumbusOS @LtChae @JarredOlson @rob-h-m

**Comment by rob-h-m** [comment]
Moved to https://github.com/SmartColumbusOS/scos-joomla/issues/15 - closing this version of the card
