### ISSUE TITLE
SPIKE: Building a push gateway

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#247]
#### Background: 

In order to ingest the CVE data (and other use cases), we know that we need to build a push gateway.  In our conversations with Kapsch (CVE sensor aggregator), we have learned that the sensors will be pushing data to the aggregator every .5 second or so.  Once the aggregator receives the data, it will then be pushed to the OS for ingestion.  

As far as the CVE data specifically is concerned, it will be pushed as JSON to a docker image with encoded metadata and payload that will then push to the OS.  

#### Scope: 

- Research how we would go about building a push gateway to first accommodate the CVE data, but later accommodate other use cases where a Docker image may not be involved. 
- Discuss findings with @jeffgrunewald , @jmorris-pillar , and @carriebrinkley 
- Write appropriate dev cards for build. 

#### Tech Notes: 

- Push data will be over UDP. Suggest using the erlang builtin `:gen_udp` library; the `sockets` library wraps `:gen_udp` but may not add enough value on top of the base library.

#### Amigos: 

@jmorris-pillar , @jeffgrunewald

**Comment by jeffgrunewald** [comment]
Output cards detailed in:
- https://github.com/SmartColumbusOS/charts/issues/1 (create kapsch cmcc deployment)
- https://github.com/smartcitiesdata/smartcitiesdata/issues/382 (create basic push gateway app)
- https://github.com/smartcitiesdata/smartcitiesdata/issues/383 (create push data tables and topics)
- https://github.com/smartcitiesdata/smartcitiesdata/issues/384 (decode CV message payloads)
- https://github.com/smartcitiesdata/smartcitiesdata/issues/385 (enrich the messages)
- https://github.com/smartcitiesdata/charts/issues/148 (deployment chart for the push gateway and deploy repo)
