### ISSUE TITLE
Forklift should gracefully init

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#248]
There is an issue where when forklift initially starts, it ends up in a bad state.  We believe this is caused by forklift initiating too many processes asynchronously.  

AC:

- When forklift is deployed to production, cota and other streams continue to persist to presto without outside intervention

**Comment by rob-h-m** [comment]
@jmorris-pillar  What should the size on this puppy be?  Thanks
