### ISSUE TITLE
Spike: Investigate Creating the DoIM Dashboard with Custom Development

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#252]
_As a SCOS dev,
I want to investigate the tools we may use to create the DoIM dashboard,
So that we make good decisions about the trade-offs of taking different approaches._

#### Adaptability
- [ ] How easy is it for others to tweak?
- [ ] How easy is it to reuse?
- [ ] How easy is it to reincorporate into Discovery UI?
- Grading: 0-5 where:
0 = no effort, and 
5 = tons of effort
#### Maintainability
- [ ] How easy is it to add a new feature?
- [ ] What does the update lifecycle look like in production? 
- Grading: 0-5 where:
0 = no effort and 
5 = tons of effort
#### UX Definition
- [ ] The DoIM Task and Hour Allocation Report requirements are as follows:
- [ ] Ability to select any time range from beginning of record-to-present
- [ ] Ability to refine by outpost, task, category, work type (plan vs. 311), 
- [ ] Ability to show any increment of tasks from one-to-all (refine by)
- [ ] Task/Hours display is displayed with a split between planned/311 work, as well as Regular Time (RT) and Overtime (OT)
- [ ] Ability to export to .PDF, .CSV
- [ ] Outposts are color-coded
- Grading: 0-5 where:
0 = very confident we can build this and 
5 = not confident we can build this
#### Dev Effort
- [ ] What is our T-shirt estimate for the effort to develop this?
Grading: 0-5 where:
0 = Less than 1 pair for 1 sprint
1 = 1 pair for 1 sprint
2 = 2 pairs for 1 sprint
3 = 4 pairs for 1 sprint
4 = 4 pairs for 2 sprints
5 = More than 4 pairs for 2 sprints
#### On Brand
- [ ] How much can we make it look/feel a part of the OS? 
- Grading: 0-5 where:
0 = it can look exactly like the OS and 
5 = it’ll look nothing like the OS

### Goals of SPIKE Day: 
- Assess your given technology based on the categories outlined in the grading matrix, and assign scores based on your best impression. 
- If time allows, create a visual or some other way to talk to your findings in front of the team so that we can best make a decision. 
- At the end of SPIKE day, a decision will be made regarding what technology we will use to build out the Department of Infrastructure Management dashboard.

 #### Timebox: 9:00-3:00 on Spike Day, Wednesday Nov 6

**Comment by jdenen** [comment]
@rob-h-m These DoIM cards should be moved to the SmartColumbusOS org, shouldn't they? They are Columbus specific unless I'm missing something.
