### ISSUE TITLE
Cache bust for plot.ly update

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#258]
As an OS user 
I want for my cache to automatically clear when new updates are pushed out
So that I can take advantage of all of the features in their best state 

#### Acceptance Criteria: 

- [ ] When a user engages with plotl.y, their browser is forced to engage with the newest version

**Comment by jdenen** [comment]
@carriebrinkley @rob-h-m @jeffgrunewald 

This feels like it should be a UI/API issue. Any reason to file it here?

**Comment by carriebrinkley** [comment]
@jdenen honestly, it is there because it is my default repo when I don't know where a card should go.

**Comment by jdenen** [comment]
Ha, good to know. I'm going to push back when I notice something that doesn't feel like a good fit. 

This one feels like it should be in `react_discovery_ui`. 

@jeffgrunewald can jump in if he thinks it should go somewhere else

**Comment by rob-h-m** [comment]
Clearly @jdenen needs more to do

**Comment by carriebrinkley** [comment]
@rajones-hntb please add any details to make this card legit.

**Comment by rob-h-m** [comment]
Moved, closing this version
