### ISSUE TITLE
RFC: streaming-persisted creation

### ISSUE THREAD

**Issue by jdenen** [smartcitiesdata/smartcitiesdata#266]
**Is your feature request related to a problem? Please describe.**
As part of smartcitiesdata/charts#139, the question of how the `streaming-persisted` topic should be created came up.

**Describe the solution you'd like**
Flair (and maybe forklift) should ensure the creation of the `streaming-persisted` topic as part their startup.

**Describe alternatives you've considered**
We could create it as part of the uber chart/Kafka configuration as originally proposed in that PR.

**Comment by jdenen** [comment]
I have trouble remembering the code that I write. Forklift already does this. Flair should do it as it is refactored to use `pipeline`.

**Comment by carriebrinkley** [comment]
@jdenen is this a solved problem?  Trying to figure out what needs to be done with this card.

**Comment by jdenen** [comment]
I just merged flair's side of this yesterday. So I'm closing. Thanks for pointing it out.
