### ISSUE TITLE
RFC: De-Structure Dataset definitions

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#272]
System logic around handling different formats of the same data are difficult to maintain when the different formats have very different technical details related to successfully processing them.

Example: A shapefile is a "hosted" type (`%Dataset{%Technical{sourceType: "hosted"}}`) but its corresponding GeoJson format (supported for automatic conversion by the Odo service) expects the sourceType to be "ingest" and various components of the system take different actions based on that value (or ignore the dataset entirely based on the value).

Dataset definitions should not prescribe specific technical substructures and should only define the basic business logic shared by all forms of that datasets' specific data. Technical structures for each of that data's various supported formats should be independently stored from the Dataset container structure and linked to the "owning" dataset via an identifier.

Example:
```
%Dataset{
  id: "123-456-7890",
  business: %Business{
    owner: "234-567-8901",
    cadence: "weekly",
    contact: "Bob",
    email: "bob@data.com",
    license: "FOSS",
    ...
  }
}
%Technical{
  id: "345-678-9012",
  dataset_id: "123-456-7890",          <====== Note the ID of the owning dataset
  sourceType: "ingest",
  sourceFormat: "application/json",
  url: "somewhere.com",
  ...
}
%Technical{
  id: "456-789-0123",
  dataset_id: "123-456-7890",          <====== Note the ID of the owning dataset
  sourceType: "ingest",
  sourceFormat: "text/csv",
  url: "s3://internal-bucket.smartcitiesdatabucket.com",
  ...
}
```

(Illustrative example only as conversion between json and csv is trivial for the system)

**Comment by jdenen** [comment]
I like it.

I'd like `andi` to stitch together these multiple definitions in its view state. So when we hit `/datasets` on `andi`, you see all technical definitions for the dataset.

Also, we should think about PODMS and what effect this may have. I suspect it will actually make PODMS better, but we should think about that.
