### ISSUE TITLE
SPIKE: Performance Tests for use in Development

### ISSUE THREAD

**Issue by NathanielScottStevens** [smartcitiesdata/smartcitiesdata#288]
As a developer, I want to know when my changes to discovery api have decreased performance before going to prod, so that I don't accidentally degrade performance.

Spike out a solution that
- Allows us to easily see our performance impact before going to prod
- Allows us to see historical performance
- Takes into account changes in the environment (Most notably, the number of datasets)

Tech Notes
- Prometheus has some metrics that may be leveraged (ex: phoenix_controller_call_duration_microseconds_sum)

**Comment by NathanielScottStevens** [comment]
Benchee looks to be able to keep appending new runs over time:
![image](https://user-images.githubusercontent.com/7041844/69095821-1de58100-0a21-11ea-9c6a-7cb643d8e5b0.png)

We could keep archiving the same `save` file and resaving over it. There is probably some magic we could do to limit this, though it seems to not be a built in thing unless you tear Benchee apart and call `Benchee.load` directly

- Ben

**Comment by mcsearchin** [comment]
Woooooooooooooooooooooooooooooooooooooooo!!!!

We recommend Benchee (for now) as a simple solution for this. Here is the general idea:
- Write perf tests that hit various interesting API endpoints (via controller)
- Make Benchee save the results of those results to a `.benchee` file (see https://github.com/bencheeorg/benchee#saving-loading-and-comparing-previous-runs)
- Make it also generate an HTML output report with https://github.com/bencheeorg/benchee_html
- Archive the `.benchee` file and the `.html` report file in Jenkins job
- Next run will load previous runs from the `.benchee` file so it can include them in its `.html` run for comparison
- Some work may need to be done to make sure the comparison history in the report is a rolling window (it gets pretty slow when it gets above 10 historical runs to compare). For this, the `Benchee.load` and `Benchee.Formatters.TaggedSave` should be of use (https://github.com/bencheeorg/benchee/blob/05dbe4f5c4e2c5ae08cd8f2eddea21bea4cba196/lib/benchee/configuration.ex)

- Ben
