### ISSUE TITLE
Remove LDAP from Discovery API

### ISSUE THREAD

**Issue by mcsearchin** [smartcitiesdata/smartcitiesdata#293]
Split this card off from smartcitiesdata/discovery_ui#17.

We need to have a conversation about how we want to go about this.

The simplest thing to do would be to remove it completely.  If there is a desire to save it for possible for future use, then we need to figure out the best way to make it configurable in the current system without having to put a lot of effort into continuing to maintain and test it.

'Also, remove the cookie monster while you're at it, since we don't use cookies anymore - Jarred' - Ben

**Comment by ManApart** [comment]
I brought this up in a grooming session.
It sounds like LDAP is definitely staying around. The desire is for it to be an option alongside 0Auth so that someone can use the OS with more than 7k users and not have to pay the 0Auth cost.

**Comment by jdenen** [comment]
Do we think an entity with more than 7000 users is going to use LDAP to manage them?

A big company may use an LDAP/Active Directory to manage their 7000+ employees, but they're going to want SAML integration (and rightfully so). A city opening this up to the public is not going to use LDAP to manage more than 7000 citizen accounts.

We'd have to put a ton of code into a "create your own account with the platform" setup that's backed by LDAP. That effort is better spent toward SAML + non-Auth0 OAuth.

If we want a "create your own account with the platform" option, there are better and more traditional ways to go than LDAP. But I'd argue we're better off with OAuth + SAML.

**Comment by jdenen** [comment]
I'm not arguing for doing the non-Auth0 OAuth and SAML work now. We can continue to punt on that.

But keeping LDAP as a perceived solution to the 7000 user issue seems like a non-starter to me.

**Comment by ManApart** [comment]
:shrug: That's just what I heard from Balser/Carrie.
