### ISSUE TITLE
Add Dialyzer to Build

### ISSUE THREAD

**Issue by NathanielScottStevens** [smartcitiesdata/smartcitiesdata#304]
As an open source contributor, I want to have confidence that type specs are accurate, so that I can contribute more easily.

_AC:_
* Dialyzer results should be visible on build
* The build should not be dependent on its success

_Tech Notes:_
* Dialyzer PLT should be cached for use on subsequent builds

**Comment by jdenen** [comment]
Closing this one since there's already a "dialyzer for the umbrella" card and transferring a streams-specific one is a duplicate.
