### ISSUE TITLE
Make free text and drop down fields editable

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#324]
As a data curator
I want to be able to edit dataset metadata
So that I can easily keep all information up to date

#### Acceptance Criteria: 
- [x] Free text fields are editable 
- [x] Drop down fields are editable 
- [x] Drop down fields have the appropriate default
- [x] Clicking save sends dataset_update event with changed data 
- [x] Organization and format are not editable 
- [x] Validation that exists should still run in the backend

#### Tech Notes: 
- List of values exist in the comments 
- Ignore 140 character limit on Title 
- Ignore markdown support 
- Mockup: https://pillartechnology.invisionapp.com/share/UFUH0HI7N84#/screens/393712560

#### Amigos: 
@jakeclark , @NathanielScottStevens , @carriebrinkley

**Comment by carriebrinkley** [comment]
Values for Drop Downs: 

Format: csv, JSON, GeoJSON, xml, Shapefile, kml, ogc wms, zip 
Organization: Populated from list of organizations 
Level of Access: Private, Public
Language: English, Spanish
Benefit: Low, Medium, High
Risk: Low, Medium, High

Please consult with @jakeclark during entry regarding the ordering and default values

**Comment by ManApart** [comment]
We're going to kick the can down the road for
Benefit: Low, Medium, High
Risk: Low, Medium, High
