### ISSUE TITLE
Add validation for metadata fields 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#328]
As a data curator
I want for information that I submit to be validated
So that I can ensure technical accuracy

#### Acceptance Criteria:
- [ ] Validation is in place

#### Tech Notes:
- Validation that exists should still run in the backend
- Mockup: https://pillartechnology.invisionapp.com/share/UFUH0HI7N84#/screens/393712560

#### Amigos:
@jakeclark , @NathanielScottStevens , @carriebrinkley

**Comment by NathanielScottStevens** [comment]
TODOs
* Get list of all expected validations
* Figure out why empty fields aren't getting persisted
