### ISSUE TITLE
RFC: make SmartCity.Dataset.Technical.Schema be a JSON schema so it sucks less

### ISSUE THREAD

**Issue by bbrewer-forge** [smartcitiesdata/smartcitiesdata#334]
**Is your feature request related to a problem? Please describe.**
With the current schema specification for SmartCity.Dataset.Technical.Schema we have some limitations:
- non-standard
- implementation to process it is a bit funky
- can't handle arrays of arrays

**Describe the solution you'd like**
Just use JSON Schema as it solves all of these problems
https://json-schema.org/learn/getting-started-step-by-step.html

It has pretty wide support, including GeoJSON - https://www.jsonschemavalidator.net/

**Describe alternatives you've considered**
XSD ;)

**Additional context**
We'd probably only want to support the basic implementation and avoid the reference stuff it can do for starters.

**Comment by jdenen** [comment]
Why not make the whole dataset definition JSON schema?

**Comment by bbrewer-papa-x** [comment]
Whoa, whoa, slow your roll there big boss man

**Comment by bbrewer-papa-x** [comment]
But yeah, that too?
