### ISSUE TITLE
Fix XSS warning when upgrading sobelow

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#335]
**Describe the bug**
Upgrading Sobelow to the latest version (0.9.x) reveals an XSS.SendResp warning that causes CI to fail.

Sobelow should be upgraded and the issue resolved accordingly or flagged to be ignored if it is not a concern.

**To Reproduce**
1. Upgrade sobelow in mix file.
2. run `mix sobelow`
3. see XSS.SendResp warning

**Expected behavior**
We should not be vulnerable to XSS attacks.

**Tech Notes:**
- This is in discovery_api

**Comment by bbrewer-papa-x** [comment]
The only takeaway from this is that our datasets, which are considered a trusted source, could include javascript that we might send back to the users of the API. We're currently rendering this safely in Discovery UI, but return it wholesale from the API. In any case, we could validate that no script is injected via ANDI into description or other fields. However, this is unlikely to be a priority as ANDI has a pretty restricted user audience at the moment.
