### ISSUE TITLE
Read event from event stream topic

### ISSUE THREAD

**Issue by kcarra** [smartcitiesdata/smartcitiesdata#342]
Summary: As Evita the Evaluator I would like to be able to access every event on the event stream from the time of inception to now so that I can hand them to Auditors. 

AC

- [x] log events from event stream to show that events are being consumed by Estuary
- [x] Make logging level configurable.

**Comment by rajones-hntb** [comment]
it would be nice if this were configurable; it would be incredibly noisy for production code to log each event, perhaps at info / debug level?

**Comment by kcarra** [comment]
I've added that AC.
