### ISSUE TITLE
Estuary creates an events table on startup

### ISSUE THREAD

**Issue by kcarra** [smartcitiesdata/smartcitiesdata#343]
Summary: As Dave the developer I would like to have a table in a database to store the events into so that I don't run out of memory storing events. 

AC:
- [ ] Table is only accessible to privileged users
- [x] Table exists and has proper columns
- [x] All dataset top level fields are their own column

**Comment by sukaant** [comment]
We should create a new card for "Table is only accessible to privileged users" and should be played after CD.

**Comment by sukaant** [comment]
Card created for first AC, https://github.com/smartcitiesdata/smartcitiesdata/issues/369
