### ISSUE TITLE
Events can be inserted into events table

### ISSUE THREAD

**Issue by kcarra** [smartcitiesdata/smartcitiesdata#344]
Summary: As Dave the developer I would like to be able to persist events into the table so that they can be queried at a later time.

AC: 

- [ ] Data is inserted into table
- [ ] Error Handling logs events that fail to persist

**Comment by ManApart** [comment]
I'd move that last criteria to #343. 
(I know I know I asked for it on this card, but I was wrong).

**Comment by kcarra** [comment]
Done.

**Comment by ManApart** [comment]
Why was this guy re-opened?

**Comment by rob-h-m** [comment]
My understanding is, it was moved into the Done column before it was actually Done.
________________________________
