### ISSUE TITLE
Master Chart for OS Local Dev

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smartcitiesdata#38]
"As a developer implementing the Smart Cities data platform, I want an easy way to run the entire system on my machine.

Acceptance Criteria:
* All apps can be deployed locally using a single chart
* Points to development tags of apps in docker hub
* Include all dependent services as dependent charts
* Any work that is not complete has an associated card written for it

Technical Notes:
* Depends on open sourcing charts
* Default values should already have targeted minikube in the individual charts
* Dependent services (as of today) include: OpenLDAP, Redis, KDP components

06-24-19: Migrated from SMRT-1373"

**Comment by ManApart** [comment]
https://github.com/smartcitiesdata/reaper/issues/116

**Comment by ManApart** [comment]
Multiple cards were written during this card's life. They (and the final 'put a bow on it' card) can be found in smartcitiesdata/project#109
