### ISSUE TITLE
Create a push gateway application

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#382]
#### User Story
As a data aggregator, I want the ability to consume high-volume, high-velocity data via direct push

#### Acceptance Criteria: 
- [ ] listens on configurable UDP port
- [ ] received messages are json decoded and logged out
- [ ] should log the "payload" field of the pushed messages as a binary string

#### Tech Notes: 
- application uses erlang's `gen_udp` active _N_ mode to avoid being flooded with messages (explicitly control backpressure)
- This does not include the deployment of the application

#### Amigos: 
@jeffgrunewald , @JarredOlson

**Comment by ManApart** [comment]
When we groom this card it'd be nice to see if we could break it down.
