### ISSUE TITLE
CV push gateway decodes message payloads

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#384]
#### User Story
As a connected vehicle data consumer,
I want my CV data decoded to human-readable values
So that I can do useful analysis on it

#### Acceptance Criteria:
- [x] CV push gateway includes native ASN decoder for CV messages
- [x] decode payload field and serialize result to JSON
- [x] update dataset definition to include schema for received messages
- [x] basic information from message (timestamp, source device, message type, message body as json string) is stored at the top-level of the ingested message output by the gateway app

#### Tech Notes: 
- kitt is a native elixir/erlang library available on hex: hex.pm/packages/kitt

#### Amigos:
@jeffgrunewald , @JarredOlson

**Comment by bbrewer-papa-x** [comment]
for dataset definition, schema will need to include (paraphrase):
- messageType: string
- messageBody: json
- timestamp: timestamp
