### ISSUE TITLE
SPIKE: How should CV messages be de-structured for ingest?

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#385]
#### User Story
How might we de-/re-structure ingested CV messages for insertion into the presto backend for easier analysis and retrieval of data?

#### Acceptance Criteria: 
- [x] Review the structure of each message type, prioritizing the MAP, SPAT, and BSM message types as the most common to be received.
- [x] Recommended schema / storage format for CV message permanent storage

#### Tech Notes: 
- There are several types of CV messages, each with a different structure
- Should the raw json of the decoded messages be stored unmodified?
- Should the json messages be converted to some form of well-known text?
- Can any common elements from the messages be pulled up to the top-level of _every_ message to become its own column?

#### Amigos: 
@jeffgrunewald , @JarredOlson , Hong Li

**Comment by carriebrinkley** [comment]
@jeffgrunewald add samples of messages

**Comment by jeffgrunewald** [comment]
Sample messages (contained within Message Frame wrappers) can be found here: http://caconnectedvehicletestbed.org/index.php/datasample.php

**Comment by cameronmarsh** [comment]
From Ram: ```BSM messages are not typically correlated with any other messages. They are interpreted individually to identify the vehicle trajectory, speed, heading, etc

SPaT and MAP messages are correlated using the signal groups.

MAP messages defines the signal group assigned to each maneuver (through, right, left, shared left and through, etc.,) and assigns them to respective lanes.

SPaT message provides information about the signal phasing of each signal group at an intersection.

Typically, MAP messages are received at a frequency of 1 per second. BSM and PSM messages are transmitted at a frequency of 10/sec. Signal Request Message (SRM) and Signal Status Message (SSM) are sent only once per each request.

SPaT message frequency varies between 1/sec - 1/5 sec depending on the use case.

Similar to BSM messages, PSM messages are also not correlated with other messages. (edited) 

However, GPS field in PSM and BSM are used to see if they are in the vicinity of a signalized intersection using the MAP message lane boundaries.

so there is not direct field to field correlation between MAP and BSM/PSM.```

**Comment by cameronmarsh** [comment]
**Can any common elements from the messages be pulled up to the top-level of every message to become its own column?**

Based on Ram's input, it seems that different messages (possibly with the exception of MAP and SPAT messages) should be stored in separate tables. There are no fields that relate all message types in a comprehensible way. Instead, it seems like the best option would be to construct a different schema based on message type, depending on where the data that is considered valuable lies within the message structure

**Comment by cameronmarsh** [comment]
**Should the raw json of the decoded messages be stored unmodified? 
Should the json messages be converted to some form of well-known text?**

There is a lot of variation in structure based on different messages, and the most valuable parts of each message are usually not at the top level. Much of this data is also hierarchical. Unless we want  to implement a way to parse each of these message types, it seems the best solution would be to have a schema based on messages' top-level fields with the values inserted as json strings. 

For example, the most valuable part of BSM messages is the `coreData` field (https://hexdocs.pm/kitt/Kitt.Message.BSM.CoreData.html#t:t/0), which is made up of fields that are mostly maps. If we don't want to parse all of the messages' subtypes, we probably don't want to parse any of their values.
