### ISSUE TITLE
Reaper handles struct upgrades to quantum jobs

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/smartcitiesdata#387]
#### User Story
Currently reaper will crash if a dataset definition that reaper has stored in a quantum job is upgraded. Reaper should be able to parse out of date structs and upgrade them to its current version.

#### Acceptance Criteria: 
- [x] Reaper does not have stored jobs crash when a struct version is upgraded
- [x] Reaper handles failed quantum job loads more gracefully

#### Amigos: 
@carriebrinkley, @ManApart or @NathanielScottStevens, @JarredOlson

**Comment by rob-h-m** [comment]
@JarredOlson will investigate further
