### ISSUE TITLE
Discovery API and Discovery UI can talk to the system in Docker

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/smartcitiesdata#41]
As a developer implementing the Smart Cities data platform, I want an easy way to run the entire system on my machine.

A developer should be able to run an app with `iex -S mix` and connect to the rest of the system running in docker on their machine.

Acceptance Criteria:
- Discovery API (run through iex) is able to communicate with docker
- Discovery UI (run through npm) is able to communicate with discovery-api (in docker)
- Minimum of configuration changes

Technical Notes:
- Configuration should be done in integration.exs
- Ports need to be exposed
- Phoenix apps may need to have a host file changed

**Comment by rob-h-m** [comment]
rejected 08/14/19 by Carrie and Johnson
