### ISSUE TITLE
Forklift fails to re-initialize dataset processing after compaction

### ISSUE THREAD

**Issue by mcsearchin** [smartcitiesdata/smartcitiesdata#430]
**Describe the bug**
When compaction runs for a dataset its data reader is terminated, the compaction is run, then the reader is re-initialized in order to continue dataset ingestion. The re-initialization step fails with a `KeyError` message.

```elixir
** (MatchError) no match of right hand side value: {:error, {%KeyError{key: :dataset, message: nil, term: []}, [{Keyword, :fetch!, 2, [file: 'lib/keyword.ex', line: 389]}, {Forklift.MessageHandler, :init, 1, [file: 'lib/forklift/message_handler.ex', line: 16]}, {Elsa.Group.Worker, :init, 1, [file: 'lib/elsa/group/worker.ex', line: 75]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
```

**To Reproduce**
1. Run compaction

**Expected behavior**
Datasets should successfully re-initialize after compaction.

**Screenshots**
N/A

**Additional context**

**Comment by carriebrinkley** [comment]
@mcsearchin we (Jarred and I) are looking for a little more context on this.  Our understanding is that compaction is currently working.
