### ISSUE TITLE
Add base API URL testing 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#449]
As a data curator, I want to be able to add an API URL and test whether it is working so that I can more efficiently obtain data to ingest. 

Acceptance Criteria: 
- [ ] Can edit/view API URL
- [ ] Can test URL
- [ ] Displays status
- [ ] ~~Make status expandable to display the whole message~~ HEAD requests do not return a body
- [ ] Can save changes

Tech Notes:
- Comp: https://aidigital.invisionapp.com/share/UFUH0HI7N84#/screens/389646420
- Does not include adding the stepper

Amigos: 
@NathanielScottStevens , @ramboyapati , @jakeclark

**Comment by ManApart** [comment]
I'm not sure which API URL we are testing here.
Is this the source URL of the data set, or a URL in Andi, or a URL in discovery API?
Is the idea that you press a button and the source url + configuration you've created for this dataset is called and you can see what data you get back (before our system does any transformation)?

**Comment by NathanielScottStevens** [comment]
It'll be clearer when you see the mockup, but it is the url that reaper will be retrieving the data from. It is just to validate that we can get a 200 from the url before submitting the dataset to the system.

**Comment by ManApart** [comment]
Makes sense. Could we link to the mockup from one of these issues/ the epic?
