### ISSUE TITLE
Add params and headers for URL uploads

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#450]
Acceptance Criteria: 
- [ ] Can view/edit query params
- [ ] Can view/edit headers
- [ ] Headers and query parameters are sent when <test> is clicked
- [ ] When accessing already ingested datasets, the params and headers will auto-populate

Tech Notes: 
- Ignore secret and URL preview
- When in doubt, see how Postman behaves
- Comp: https://aidigital.invisionapp.com/share/UFUH0HI7N84#/screens/389646420

Amigos: 
@ramboyapati , @jakeclark

**Comment by mcsearchin** [comment]
Questions:
- how to delete rows?
- how to add rows?  (plus button, or auto-resize like postman)
- allow user to type query params in base URL box?

**Comment by ramboyapati** [comment]
1. It would be nice to have a **X** button to the right of the last column to delete a row
2. Auto-resize like postman is preferred.
3. Allowing user to type parameters in the base URL is fine. Would these parameters be auto-populated in the parameters section below? or is the first iteration to only have a base URL?

**Comment by mcsearchin** [comment]
Thanks Ram.  We talked through these questions with @jakeclark and we'll be building the 'easiest' solution first.  So...

- We will allow the user to delete rows with an 'X' on the right-hand side of the row
- We will use a plus button for now to add a row (auto-resize can be added later)
- For now, we will strip query parameters out of the URL box.  We can add the feature later where adding query parameters in the URL input dynamically adds those query parameters in the table below.
