### ISSUE TITLE
SPIKE: Reaper doesn't use EEX

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#452]
As a part of the Data Curator UI, we need to be able to gracefully handle secrets and their being stored in vault without the dependency on EEX. 

Questions to Answer: 
- How do we handle this for secrets?
- How do we handle this for calculated fields i.e. dates?

Tech Notes:

Amigos: 
@NathanielScottStevens , @JarredOlson

**Comment by jeffgrunewald** [comment]
Discussed during entry with @mcsearchin and @bbrewer-papa-x 

Proposed solution will adapt the dataset definition that tracks connection details (query params, uri, path params, headers, etc) to a json-like structure with a list of "connection components". Those connection components will either be a string or a "provider" map construct that evaluates to a string. During extract events, Reaper will reduce over the list of components to build the connection string for the query.

This "provider" library should be in_umbrella but independent of any of the applications so both reaper, andi, and any others requiring access to these runtime values can make use of the functions equally.

The user will be presented with a JSON interface for selecting providers that will equate to versioned Elixir structs on the backend to allow for migration at a later time.

Early proposed providers:
- date (optional offset, optional format, defaults to utc)
- date_range (optional format, defaults to utc)
- auth_vault, keyed off of dataset id
- "complex" type that can extract multiple values from a configuration or secret repo (such as both username and password from a single vault secret)

Vault could be abstracted away from the system in multiple ways to allow for storing in simple key/value stores for testing (such as redis) and from cloud-provider secret management services like KMS or secrets manager.

Examples:
```
{
  provider: "chain",
  [
    {provider: "auth_vault", opts: []},
    {provider: "blah"}
  ]
}

{
  type: "uri",
  opts: {
    protocol: "string",
    base: "string",
    path: "list"
  }
}

sourceUrl: {
  provider: "uri",
  opts: [
    protocol: "https",
    base: "mmapi.etch.app",
    path: [
      "metrics",
      {provider: {"date": "v1"}, opts: {"offset": -1},
      "Pivot"
    ]
  ]
}

queryParams: [
  start_date: {
    provider: {"date": "v1"},
    opts: {}
  },
  _complex: [
    {
      provider: vault_auth,
      keys: {
        username: "/username",
        password: "/password"
      }
    }
  ]
]
```

**Comment by jeffgrunewald** [comment]
Another considered raised during exit is: if the non-secret connection details for the dataset are still displayed on the UI, how to present values that are not static strings (tokens, username/password, interpolated dates/date ranges, etc).

One option would be to show the current value evaluated by the provider as the user is viewing it (unless it is a secret value) or explicitly call out the value is being supplied by a dynamically retrieved or calculated variable.
