### ISSUE TITLE
Discovery_api supports API keys

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#455]
As Carlos I would like to be able to utilize private datasets that I have access to with tableau so that I can increase agency efficiency.

Acceptance Criteria: 
- [ ] discovery_api can create, persist, and manage API keys
- [ ] Key consists of generated UUID
- [ ] Key is passed in through a X-API-Key header
- [ ] All secured endpoints allow the API key to be used
- [ ] Encrypt the darn thing

Tech Notes:
- Shouldn't include any user identifiable fields

Amigos:
@LtChae , @JarredOlson

**Comment by mcsearchin** [comment]
- use self-signed very-long-lived token that has the same subject ID as a user in auth0
- consider only letting a user obtain this type of token if they have some special permission (either in our data store or in auth0?)
- use some kind of revision number that is a custom claim on the token and that we store in association with the user - these should match for the key to be legit
