### ISSUE TITLE
Allow users to enter an API key 

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#456]
Acceptance Criteria: 
- [ ] User can enter API key through web data connector
- [ ] Web data connector uses the API key to make the call (even in Tableau server)

Tech Notes: 
- Helpful documentation exists on the connector
- You'll need to have Tableau on your machine 

Depends on #455 D_api supports API keys

Amigos: 
@JarredOlson , @LtChae

**Comment by bbrewer-papa-x** [comment]
Is this blocked by https://github.com/smartcitiesdata/smartcitiesdata/issues/455 ?
