### ISSUE TITLE
Discovery API should have configurable API_HOST used in URL and responses

### ISSUE THREAD

**Issue by kennyatpillar** [smartcitiesdata/smartcitiesdata#464]
#### User Story
As a developer running a Discovery API instance, I want to be able to configure the API_HOST and base url so that any response that includes a URL includes the full URL so that the API is easier to work with.

#### Acceptance Criteria: 
- [ ] Discovery API config files should have api_host
- [ ] Any API that includes a URL in the response (like the presigned URL for private datasets) should have full URLs rather than relative URLs.

#### Tech Notes: 
- As part of this card, URLs should be updated to be full, not relative.

#### Amigos: 
@carriebrinkley @mcsearchin

**Comment by carriebrinkley** [comment]
Included in scope of monitoring #95
