### ISSUE TITLE
Replace WSTA in examples

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#466]
#### User Story
As a data consumer, I want to have easy to use instructions for testing data-streams, so that I can understand what value I can get from streaming data sets.

#### Acceptance Criteria: 
- [ ] A new tool is chosen to replace wsta
- [ ] This tool is used to replace examples on streaming dataset details pages
- [ ] Cota about this map page is updated.
- [ ] The cota_stream alias in team configs is updated to use this new tool
- [ ] Search all repos for wsta in case i forgot to mention something
- [ ] Update: https://www.smartcolumbusos.com/data-stories/streaming-data-feed-shows-riders-where-their-bus-is-in-real-time

#### Tech Notes: 
- This might not be the best solution but I got this to work:

echo '{"topic":"streaming:central_ohio_transit_authority__cota_stream","event":"phx_join","payload":{},"ref":"1"}' | websocat -n 'wss://streams.smartcolumbusos.com/socket/websocket'

This will need to add in the ping stuff to keep the connection open I think.  The deliverable of this card does not need to use this tool but I wanted to prove that at least one tool worked before sending someone looking.

#### Amigos: 
@JarredOlson @abrock-accenture

**Comment by jdenen** [comment]
Don't know if you've seen it, since the author is not putting anything on `wsta`'s repo, but he's moved focus to `wurl`. It looks pretty solid.

https://github.com/getwurl/wurl

It has a plugin model, and the ping stuff is built in there.

https://github.com/getwurl/wurl-tools
