### ISSUE TITLE
Put the darn shuttle on a map

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#487]
It has been requested that we make the Easy Mile shuttle publicly accessible on a map similar to how it was done for May Mobility. 

Look at this commit in cota-streaming-ui repo to see how we did it for the old shuttle:

`git log -p f08d07adf990bf5f9659ed8765c1dccad4e78ec1`

#### Acceptance Criteria: 
- [ ] The shuttle exists in the drop down as "SMRT - Linden LEAP"
- [ ] The appropriate shuttle icon is displayed on the map when the user selects it from the drop down
- [ ] The feed is populated from the Easy Mile real-time dataset

#### Tech Notes:
- @jakeclark to provide image
#### Amigos: 
@JarredOlson , @carriebrinkley

**Comment by jakeclark** [comment]
Option 1: 
![map-marker-easymile](https://user-images.githubusercontent.com/430082/73454881-fa9e5280-433c-11ea-952c-d6e1061aab07.png)

We had a version of this marker for the May Mobility shuttle. The downside to this is that the easy mile logo will be hard to read at this size. I am retrofitting the marker with the shuttle icon next.

**Comment by jakeclark** [comment]
This is a version with the shuttle icon: 
![map-marker-easymile2](https://user-images.githubusercontent.com/430082/73455288-bc556300-433d-11ea-9a89-a47bc344eb7f.png)

**Comment by jakeclark** [comment]
Last one, with a take on something that looks like an autonomous shuttle:
![map-marker-easymile3](https://user-images.githubusercontent.com/430082/73455488-2d951600-433e-11ea-9fc9-a6b6e84c770b.png)

**Comment by jakeclark** [comment]
Version with icon Jeff sent: 
![map-marker-easymile-shuttle](https://user-images.githubusercontent.com/430082/73458487-5d92e800-4343-11ea-9d9d-ac42318d87a3.png)
