### ISSUE TITLE
Make data.json endpoint adhere to Project Open Data Schema

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#506]
As Connor I would like to utilize the provided data.json so that I can utilize the public datasets available in the operating system in another data platform (e.g. data.world).

Acceptance Criteria:
- [ ] `issued` is ISO8601 format
- [ ] data.json endpoint performance improvement (consider utilizing `DiscoveryApiWeb.Plugs.ResponseCache`)
- [ ] email is sent to Dean letting him know this work has been completed.  (Work with Jarred on this)
- [ ] Check Project Open Data Schema (https://project-open-data.cio.gov/v1.1/schema/) for any other anomalies that we might have.

**Comment by ScottMillard** [comment]
Notes from discussion with Jarred:

- No codifed migration code necessary, get from andi endpoint, update, and post back to andi.
- Defaults:
`
"issuedDate": "2019-05-01T00:00:00-0500",
"benefitRating": 0.5,
"riskRating": 0.5,
"publishFrequency": "once",
"language": "en-US",
"license": "http://www.opendefinition.org/licenses/cc-by"
"description": "No Description Available" or  "description": <set to title>
"accrualPeriodicity": "irregular"
Contact Point Email: smartcolumbusos@columbus.gov
Contact Point Name: Smart Columbus
`
