### ISSUE TITLE
Ingest XML files that are currently remote

### ISSUE THREAD

**Issue by SSackey** [smartcitiesdata/smartcitiesdata#53]
"As Connor the Data Consumer,
I want to consume all types of data directly from the Operating System,
So that I have a consistent and complete experience accessing data.

 Break down and groom cards
 * Ingest XML datasets that are currently remote

06-24-19: Migrated from SMRT-1257"

**Comment by jdenen** [comment]
@rob-h-m
This is specific to Columbus and should move to SmartColumbusOS
