### ISSUE TITLE
Saving a visualization you don't own creates your own copy of it

### ISSUE THREAD

**Issue by LtChae** [smartcitiesdata/smartcitiesdata#541]
#### User Story
As Connor
When someone shares a visualization with me
I would like to be able to save a copy of it with or without my own changes
So it shows up on my workspace list
So I can finally be happy about something this year

#### Acceptance Criteria: 
Given a visualization that belongs to another user, when I save the visualization
- [ ] It should assign it a new ID
- [ ] It should assign it whatever title I gave it during save
- [ ] It should not change the original visualization
- [ ] The visualization should show up in my workspace list at https://discovery.smartcolumbusos.com/user

#### Tech Notes: 
- There is already a piece of logic in the API that determines if a user owns a visualization being saved. Should be pretty simple to do some magic there

#### Amigos: 
@LtChae @carriebrinkley @cameronmarsh @bbrewer-papa-x

**Comment by cameronmarsh** [comment]
After discussion with Jake Clark we are opting to add a "Save A Copy" button.  We will use the same API to do creates/updates, but will need to determine if the user is allowed to save a copy on the front end.  Scenarios:

- If the user is not logged in, we show a popup similar to the "Saved Workspaces" button saying "You need to be logged in to save a workspace."
- If the workspace is brand new, the Save button is enabled and the Save a Copy button is disabled.
- If the workspace has already been saved, and the user is the owner, the Save and Save a Copy buttons are enabled.
- If the workspace has already been saved, and the user is NOT the owner, the Save button is disabled and Save a Copy button is enabled.
