### ISSUE TITLE
Add New Field to Schema

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#579]
As the data curator I would like to be able to add new fields to my schema definition.

AC:

- [ ] Plus button opens modal to add a new field with the name, type child-of fields enterable.
- [ ] After adding new field the tree should have that item selected and the "right form" should be visible/editable.
- [ ] Add New Field should default the `child of` to `Top Level`.
- [ ] `child of` field can only be added as a child of the root or map fields.  A list of maps is considered a map field

Amigos:
@LtChae , @jakeclark , @carriebrinkley 

https://aidigital.invisionapp.com/share/UFUH0HI7N84#/screens/398146324

**Comment by bbrewer-papa-x** [comment]
Question from playing edit card: should changing a non-map (type or subtype) field to a map field trigger this dialog to add a sub-field? Or do we put that off as another feature?
