### ISSUE TITLE
Linden LEAP Boardings/Alightings

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#585]
Metrics to include:
- [ ] ~Boardings by station (attributes.number_of_passengers)~
- [ ] ~Alightings by station (attributes.number_of_passengers)~
- [x] Ramp deployments per station (attributes.ramp)
- [x] Average wait time per station ~(attributes.activity.progression.stops.waiting_time)~

Notes:
- ~The boardings/alightings calculation will be similar to the ridership calculations.  We will need to calculate how many get off at a stop with decreasing values and then how many get on with increasing values.~

**Comment by dunson062786** [comment]
removed boarding/alighting requirements for this card since this sensor wasn't turned on.

**Comment by dunson062786** [comment]
https://discovery.smartcolumbusos.com/visualization/vdwzwp0e and https://discovery.smartcolumbusos.com/visualization/5mnw43tt
