### ISSUE TITLE
Linden LEAP Travel

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#586]
Metrics to include:
- [x] Time between shuttles at stations
- [x] Average travel time between stations
- [x] Average speed between stations (attributes.speed)
- [x] Average speed by direction (northbound and southbound) (attributes.speed)
- [x] Daily distance traveled (attributes.mileage)
- [x] Weekly distance traveled (attributes.mileage)
- [x] Monthly distance traveled (attributes.mileage)
- [x] Distance traveled to-date (attributes.mileage)
- [x] Distance traveled before AM break, between breaks, after PM break (attributes.mileate)

Notes:
- The first bullet is important to measure and evaluate headway for the project.  It needs to calculate the time from when the last shuttle left and the next one arrives. 
- The second bullet needs to calculate the difference in time between the arrival at a station and the departure from the previous station.  This should be broken out between the labeled stations: 
1.) St. Stephens - Douglas SB
2.) Douglas SB - Rosewind SB
3.) Rosewind SB - Linden Transit Center
4.) Linden Transit Center - Rosewind NB
5.) Rosewind NB - Douglas NB
6.) Douglas NB - St. Stephens

**Comment by dunson062786** [comment]
We already have a visualization for the first checkbox "Time between shuttles at stations" (https://discovery.smartcolumbusos.com/visualization/5mnw43tt)
We already have a visualization for the second checkbox "Average travel time between stations" (https://discovery.smartcolumbusos.com/visualization/u8rf9woh)

**Comment by dunson062786** [comment]
Average speed between stations: https://discovery.smartcolumbusos.com/visualization/xypwmnv8
Average speed by direction: https://discovery.smartcolumbusos.com/visualization/p8ne75ud
Daily distance traveled: https://discovery.smartcolumbusos.com/visualization/73gme5sk
Weekly distance traveled: https://discovery.smartcolumbusos.com/visualization/65kfqvby
Monthly distance traveled: https://discovery.smartcolumbusos.com/visualization/2dfvedcp
Distance traveled to-date: https://discovery.smartcolumbusos.com/visualization/h0j1af89
Distance traveled before AM break, between breaks, after PM break: https://discovery.smartcolumbusos.com/visualization/xxj9hbtw
