### ISSUE TITLE
Linden LEAP Autonomy

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#587]
Metrics to include:
- [x] Number of interventions (while greater than 0 mph) (attributes.mode, attributes.speed) (Skip for now - similar to disengagements report)
- [x] Average autonomy vs. manual (attributes.mode) for entire route and between stations
- [x] Frequency of reasons for disengagement (attributes.disengagement_reason)

Notes: 
- The reason for removal of 0 mph disengagements is that the operators are required to e-stop for breaks or to wait for a boarding passenger.  We are only interested in disengagements while moving.
- Number of interventions per day(ask Jeff)
- Average autonomy vs manual per day (ask Jeff)
- update route segment visualization in dev account.

**Comment by dunson062786** [comment]
Here are the links to the visualizations on the dev account:

https://discovery.smartcolumbusos.com/visualization/mbxr989v
https://discovery.smartcolumbusos.com/visualization/puz2ma7g
https://discovery.smartcolumbusos.com/visualization/d5xp73r2
https://discovery.smartcolumbusos.com/visualization/7xogql8n
