### ISSUE TITLE
Linden LEAP Battery

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#588]
Metrics to include:
- [x] Battery start %
- [x] Battery end %
- [x] Daily exterior temperature start
- [x] Daily exterior temperature end
- [x] Daily exterior temperature average

Notes: 
- The battery evaluations should be done for each time the vehicle is turned on and off. Then we can compare it to the mileage and time during operation to evaluate performance of the battery.

**Comment by dunson062786** [comment]
Battery Start/End, Temperature Start/End https://discovery.smartcolumbusos.com/visualization/usexux8a
Daily Average Temperature: https://discovery.smartcolumbusos.com/visualization/nw1g1sg9
