### ISSUE TITLE
Motivated Intruder Testing Task#1- Verification of Accidental Inclusion of PII in the OS datasets

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#596]
As the Smart Columbus Chief Privacy Officer, I would like a privacy test to be conducted that is focused on verification of any accidental PII inclusion in the datasets ingested in the OS, so that I can apply necessary controls if required. In case of no PII, it helps to me to validate that the existing controls are working in keeping private data out of the OS.

Task#1 focuses on verification of accidental inclusion of PII in the datasets in the OS. This refers to any fields having PII (both direct and indirect PII should be identified).

AC:
1. Identify a list of datasets that have PII in them

Link to doc:

https://docs.google.com/document/d/1xGKv6VWAM3LWT47JXDLukO4O83Cw3_yXOMxPPUUVVuM/edit?ts=5e4eadcf

Amigos: 
@ramboyapati , Warner Moore

**Comment by warnerAWESOMEmoore** [comment]
Data sets reviewed for possibly PII and documented in the Google Form. Will review findings with Ram, this is good to close.

**Comment by warnerAWESOMEmoore** [comment]
@ramboyapati let's discuss Sukaant's findings. He believes one finding could be PII and the other is publicly available.

**Comment by warnerAWESOMEmoore** [comment]
Ram's review concluded that Sukaant's findings were of publicly available of information.
