### ISSUE TITLE
Motivated Intruder Testing Task#2- Use of Information of the OS to identify a user through 3rd party searches (web, public archives, open records, etc.,) 

### ISSUE THREAD

**Issue by ramboyapati** [smartcitiesdata/smartcitiesdata#605]
#### User Story
As the Smart Columbus Chief Privacy Officer, I would like a privacy test to be conducted that is focused on using field level information in the datasets ingested in the OS to identify a user through a combination of datasets on the OS or third party sources, so that I can apply necessary controls if required. In case of no information on the OS can be used to identify a user, it helps to me to validate that the existing controls are working in keeping private data out of the OS.

#### Acceptance Criteria: 
- Identify a list of datasets (relevant fields) that has information which when used with a third party source (examples include, but not limited to a web search, open dataset on other websites, social network search, electoral search , etc.,) could identify a user

#### Tech Notes: 
Link to the Motivate Intruder Testing Process document is
https://docs.google.com/document/d/1xGKv6VWAM3LWT47JXDLukO4O83Cw3_yXOMxPPUUVVuM/edit?ts=5e4eadcf

#### Amigos: 
@ramboyapati, Warner M.

**Comment by warnerAWESOMEmoore** [comment]
Need to create and attempt reidentification exercises as defined in the process. More work to be done.
