### ISSUE TITLE
DoIM Dashboard Feedback

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#633]
Design:
- More prominent header
- Move Last Year comparison to subheader level
- Graph:
25T should be 25TH
List units, add percentage to pop-up
- Column Totals needed should be added if possible.
 
 
Functionality:
- For DOIMv1, there are currently 6 sheets. If all 6 sheets are not intended to be visible as separate tabs, they should be unchecked at publication time. With multiple “detail” tabs, the main page should be moreso a summary page. The pie chart does not adjust based on filters, but it should if possible.
- Maintenance zone filter should be added if possible.
- The tabs are already useful for navigation, so the action buttons at the bottom could be more useful by carrying over the selection to other tabs.

**Comment by LtChae** [comment]
Pending question to DOI

**Comment by LtChae** [comment]
Blocked again, pending questions.
