### ISSUE TITLE
Standup Elasticsearch Service

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#639]
Standup an Elasticsearch Service Instance

AC:
- [x] Create an Elasticsearch Service Instance defined in common as a feature
- [x] Create Instance with 3x nodes
- [x] Use t2.small.elasticsearch
- [x] Should not be publicly accessible.  Only allow traffic on :9200 from within the EKS cluster
- [x] Kibana interface should be accessible from the VPN

Stretch Goals:
- [ ] Encryption At Rest.  If this is an easy setting please enable it.

Tech Note:
- [x] Output the Elasticsearch URL as a terraform output
- [ ] Expose as an external services similar to redis

Amigos:
@jakeclark @carriebrinkley @JarredOlson

**Comment by bbrewer-papa-x** [comment]
Questions:
- the instance size we chose does not allow for encryption at rest. what do?
- backup strategy? there appears to be nothing baked in, but we could attach something to the ebs itself
- encryption in transit - I have it turned off for my test single-node cluster, but it should be a for free thing, AFAIK
- still trying to figure out if ES and Kibana are differentiated by path or port. It looks to be path at the moment :(
