### ISSUE TITLE
Keywords, Organization, and API Accessible Search

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#645]
Add the facet search capability to the new search.

AC:
- [x] Keywords are selectable
- [x] Organizations are selectable
- [x] API Accessible is selectable
- [x] Return aggregation counts as part of the response

Amigos:
@carriebrinkley @JarredOlson

**Comment by LtChae** [comment]
Blocked from Prod as Jarred works on deleting datasets from the index.
