### ISSUE TITLE
Private Datasets Search

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#646]
AC:
- [x] Private Datasets are filtered out for unauthenticated users
- [x] Private Datasets are accessible for authenticated users based on their organization association

Tech Note:
Ensure that organizations and or keywords that are associated with private datasets are not returned
Our system currently only supports a user being part of one organization.  Let's set this up in a way though that supports multiple.

Amigos:
@carriebrinkley @JarredOlson

**Comment by LtChae** [comment]
Users can be part of multiple organizations, per the schema:
```elixir
many_to_many(:organizations, Organization, join_through: DiscoveryApi.Schemas.Users.UserOrganization)
```
