### ISSUE TITLE
Sort Search

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#647]
AC:
- [x] Search is sortable by Name Asc/Desc
- [x] Search is sortable by Last Modified Desc
- [x] Search is sortable by relevance

Tech Notes:
Relevance sorting is the default in elasticsearch when no sorting options are provided.

**Comment by bbrewer-papa-x** [comment]
Some modifications may need to be done to the `datasets` index in ElasticSearch to make sure a default is assigned to datasets missing the modifiedDate field as well as the issuedDate field, as those seem to be our major pain points for things being omitted at this point.
