### ISSUE TITLE
ODOT traffic count 2020

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#666]
Using the ODOT Traffic Count dataset (https://discovery.smartcolumbusos.com/dataset/odot/traffic_counts_2016_to_2020) create a visualization that shows the following: 

- [x] Line diagram
- [x] Weekly breakdown
- [x] Demonstrates the increases and decreases of traffic counts on a weekly basis only for 2020

TN:
- Built in Plot.ly
- Save visualization and share link with @jakeclark 

Amigos: 
@JarredOlson , @carriebrinkley

**Comment by dunson062786** [comment]
https://discovery.smartcolumbusos.com/visualization/prpct37z
