### ISSUE TITLE
Parking transaction counts visualization

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#668]
Using the IPS and Park Mobile transaction datasets, create a visualization that demonstrates the following:

- [x] Split Bar Chart
- [x] Historical transaction amounts per week 2019 vs. 2020 transaction amounts per week
- [x] Percentage chance between years

TN:
- Built in Plot.ly
- Goal is to help demonstrate when the world goes back to "normal"
- Save visualization and share link with @jakeclark 

Amigos: 
@JarredOlson , @carriebrinkley

**Comment by sukaant** [comment]
Weekly Vehicle Parking Hours: https://discovery.smartcolumbusos.com/visualization/72qbdaut

**Comment by sukaant** [comment]
Dev Account: https://discovery.smartcolumbusos.com/visualization/jzfrltzd
