### ISSUE TITLE
Parking prediction validation

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#680]
AC:
- [ ] nightly check after the parking prediction model is retrained
- [ ] validates that there isn't more than a .05% change from the model the day before
- [ ] notifies in Prod Alerts if there is too big of a change

TN:
- Explore doing this with prometheus, but it doesn't have to be done that way

Amigos:
@JarredOlson , @carriebrinkley

**Comment by LtChae** [comment]
Fybr Data is likely to be very different from our model predictions at first. Not sure if we can tie success of the nightly train to how close they are.
