### ISSUE TITLE
Local in-development apps should connect to the system being run in a local docker

### ISSUE THREAD

**Issue by ManApart** [smartcitiesdata/smartcitiesdata#69]
As a developer implementing the Smart Cities data platform, I want an easy way to run the entire system on my machine.

A developer should be able to run an app with iex -S mix and connect to the rest of the system running in docker on their machine.

Acceptance Criteria:
- All other apps besides Discovery API and Discovery UI are able to talk to the rest of the system running in Docker
- Scos system test (run locally) passes for each app pulled out into iex
- Minimum of configuration changes

Technical Notes:
- Depends on #41
- Configuration should be done in integration.exs
- Phoenix apps may need to have a host file changed

**Comment by rob-h-m** [comment]
rejected 08/14/19 by Carrie and Johnson
