### ISSUE TITLE
Telemetry: Odo and Discovery Streams

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#693]
AC:
 - [x] App has Telemetry and the Prometheus reporter for it as dependencies
 - [x] All apps expose number of event-stream events handled by type and dataset id (not ignored ones)
 - [x] App's metrics can be found using the Prometheus console
    - This will require changes to the charts to allow prometheus to scrape the /metrics endpoint. We have plenty of examples, check DiscoveryAPI

Amigos:
@LtChae , @JarredOlson , @carriebrinkley 

Other useful metrics:
 - Phoenix Apps (Discovery and Andi) expose duration and count of api requests by endpoint
 - Gauge (current #) of datasets (Andi and DiscoveryAPI)
 - Count of records sent to Dead-Letters from each app (with reason and dataset id) (Reaper, Valkyrie and Forklift)
 - Count of data records processed by each app by dataset id (Reaper, Valkyrie and Forklift)
 - Gauge (current #) of record counts of datasets (Maybe emitted post-compaction?) (Forklift)
 - Erlang VM resource usage (top-k processes by app?) (All apps)
    - (Note: there doesn't seem to be a library pre-made to do this, but the info we need is available)

Telemetry
https://github.com/beam-telemetry/telemetry
Prometheus reporter for Telemetry
https://github.com/beam-telemetry/telemetry_metrics_prometheus
Useful Reading
https://samuelmullen.com/articles/elixir-telemetry-metrics-and-reporters/
Phoenix Telemetry
https://hexdocs.pm/phoenix/telemetry.html

**Comment by LtChae** [comment]
Merged into https://github.com/smartcitiesdata/smartcitiesdata/issues/693
