### ISSUE TITLE
Suggested Phrases API and Index

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#734]
AC: 
- [ ] Enable autocomplete for ElasticSearch to assist users with search terms
- [ ] Have an API endpoint that is its own endpoint for returning suggested phrases
- [ ] Uses ElasticSearch to return phrases that the user may have meant based on what they're typing
- [ ] Index is updated to contain suggested phrases

Amigos: 
@JarredOlson , @carriebrinkley

**Comment by LtChae** [comment]
Card punted on for now. We need a clearer picture of how auto-complete would work for the user.
[completion_snippets.txt](https://github.com/smartcitiesdata/smartcitiesdata/files/4788641/completion_snippets.txt)

**Comment by LtChae** [comment]
Useful reading for this topic: https://qbox.io/blog/multi-field-partial-word-autocomplete-in-elasticsearch-using-ngrams
