### ISSUE TITLE
Intrusion Detection and Monitoring for Security (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#75]
Intrusion Detection, monitoring for security (IDS/IPS in DPP) (L)
 * Assume AWS/ThreatStack

T-Shirt estimate was made on 05/31/19.
 * S: < 1 pair / .5 sprint
 * M: 1 pair / 1 sprint
 * L: 2 pairs / 1 sprint
 * XL: way >

07-02-2019 Migrated from SMRT-1326

**Comment by jdenen** [comment]
@rob-h-m
This is specific to Columbus and should move to SmartColumbusOS

**Comment by warnerAWESOMEmoore** [comment]
Good thoughts that relate to the work here:

https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcolumbusos/scosopedia/118

**Comment by bbrewer-papa-x** [comment]
Oh yeah, these are great, thanks!
