### ISSUE TITLE
OpenVPN MFA

### ISSUE THREAD

**Issue by carriebrinkley** [smartcitiesdata/smartcitiesdata#751]
One of the issues identified during the Microsolved Pen Test was that we need to require 2 forms of authentication to access our network behind Open VPN. 

AC: 
- [ ] The VPN is configured to require every user to have a minimum of two factors of authentication
- [ ] Every active user is disabled or has two factors of authentication configured

Amigos:
@bbrewer-forge , @JarredOlson , Warner Moore

**Comment by bbrewer-forge** [comment]
Docs: https://openvpn.net/vpn-server-resources/google-authenticator-multi-factor-authentication/

**Comment by bbrewer-forge** [comment]
Part of this will likely be removing the default `openvpn` user as they can't be secured with 2FA
https://openvpn.net/vpn-server-resources/recommendations-to-improve-security-after-installation/#secure-the-openvpn-administrative-user-account

Additionally, an LDAP user needs to be set up as the replacement admin, which we'll document.

Finally, if we ever need to restore the `openvpn` user as they don't require 2FA, there are directions for doing that too:
https://openvpn.net/vpn-server-resources/troubleshooting-authentication-related-problems/#Reset_default_openvpn_account_administrative_access
