### ISSUE TITLE
Firewall/WAF (t-shirt)

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/smartcitiesdata#77]
Firewall/WAF (DPP) (M)

T-Shirt estimate was made on 05/31/19.
 * S: < 1 pair / .5 sprint
 * M: 1 pair / 1 sprint
 * L: 2 pairs / 1 sprint
 * XL: way >

07-02-2019 Migrated from SMRT-1327

**Comment by jdenen** [comment]
@rob-h-m
This is specific to Columbus and should move to SmartColumbusOS
