### ISSUE TITLE
Presto Data Backup

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#776]
To increase data durability we would like to backup the presto data.

AC:
- [x] Nightly at 1:15am run a process to sync the prod bucket to the backup bucket
- [x] Enable lifecycle rule to delete objects older than 30 days
- [x] Ensure that the date and timestamp of the files are retained in the backup

Stretch Goal:
- [x] Create bucket in us-east-2

Tech Notes:
Does this running at the same time as compaction cause issues?
Do this in KDP repo

**Comment by bbrewer-forge** [comment]
Recovery test

Delete data
```sh
drop table fybr__short_north_parking_occupancy;
```

Re-PUT dataset to ANDI to get it to recreate the s3 folder and confirm the table is back
```sh
show tables like '%fybr%';
```

Restore with a sync (this one sucks, but I'm sure there are better things we can come up with if this is too tedious), where only the most recent ORC files are included by name
```sh
aws s3 sync s3://presto-storage-backup-staging/hive-s3/fybr__short_north_parking_occupancy s3://presto-hive-storage-staging/hive-s3/fybr__short_north_parking_occupancy --exclude \* --include 20200713_050004_01666_cv6sw_cd1ee35e-4594-403e-b3d4-28815b46e09b --include 20200713_050004_01666_cv6sw_b84c1b5a-3db4-4e95-bc5b-de36eb91f07b --include 20200713_050004_01666_cv6sw_89d6bcc3-57b0-497b-9932-650ff40afaa9 --include 20200713_050004_01666_cv6sw_423049fd-a829-44a4-8624-1a1aa022a410
```

Confirm that data is back
```sh
presto:default> select count(1) from fybr__short_north_parking_occupancy;
   _col0
-----------
 106788909
(1 row)

Query 20200713_141744_04758_cv6sw, FINISHED, 2 nodes
Splits: 30 total, 30 done (100.00%)
0:01 [107M rows, 4.4MB] [114M rows/s, 4.69MB/s]
```
