### ISSUE TITLE
Discovery Api  throws errors on data_write_complete events

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/smartcitiesdata#828]
**Describe the bug**
I am unsure if this causes any material problems but the discovery_api pods through data_write_complete related errors.

**To Reproduce**
1.) Restart disco_api or view its logs

AC:
- [ ] The last ingested time should be tracked correctly.

Example log:
 GenServer.call({:via, Registry, {:brook_registry_discovery_api, Brook.Server}}, {:process, "{\"__brook_struct__\":\"Elixir.Brook.Event\",\"__struct__\":\"Elixir.SmartCity.DataWriteComplete\",\"author\":\"forklift\",\"create_ts\":1596054433134,\"data\":\"{\\\"id\\\":\\\"78213fa0-94a3-45ed-8ee2-f44825e13d20\\\",\\\"timestamp\\\":\\\"2020-07-29T20:27:13.134284Z\\\",\\\"__brook_struct__\\\":\\\"Elixir.SmartCity.DataWriteComplete\\\"}\",\"forwarded\":false,\"type\":\"data:write:complete\"}"}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:989: GenServer.call/3
    (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:769: Enum.each/2
    (brook) lib/brook/driver/kafka/handler.ex:17: Brook.Driver.Kafka.Handler.handle_messages/2
    (elsa) lib/elsa/group/worker.ex:100: Elsa.Group.Worker.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {#PID<0.3095.0>, {:kafka_message_set, "event-stream", 0, 39777868, [{:kafka_message, 39777687, "data:extract:start", "{\"__brook_struct__\":\"Elixir.Brook.Event\",\"__struct__\":\"Elixir.SmartCity.Dataset\",\"author\":\"reaper\",\"create_ts\":1596054418002,\"data\":\"{\\\"business\\\":{\\\"authorEmail\\\":null,\\\"authorName\\\":null,\\\"benefitRating\\\":1,\\\"categories\\\":null,\\\"conformsToUri\\\":\\\"https://project-open-data.cio.gov/v1.1/schema/\\\",\\\"contactEmail\\\":\\\"info@easymile.com\\\",\\\"contactName\\\":\\\"Easy Mile Inquiries\\\",\\\"dataTitle\\\":\\\"Easy Mile Positions - Linden Deployment\\\",\\\"describedByMimeType\\\":\\\"\\\",\\\"describedByUrl\\\":\\\"\\\",\\\"description\\\":\\\"This dataset presents the information about the CEAV vehicle positions in the Linden Deployment.\\\",\\\"homepage\\\":\\\"https://columbus-columbus-columbus-sitecc.us.fm.easymile.com/api/public/v3\\\",\\\"issuedDate\\\":\\\"2020-02-05T00:00:00Z\\\",\\\"keywords\\\":[\\\"Autonomous\\\",\\\"Electric\\\",\\\"Shuttle\\\",\\\"First Mile Last Mile\\\",\\\"GPS locations\\\"],\\\"language\\\":\\\"en-US\\\",\\\"license\\\":\\\"http://opendefinition.org/licenses/cc-by/\\\",\\\"modifiedDate\\\":\\\"2019-05-01T00:00:00Z\\\",\\\"orgTitle\\\":\\\"Easy Mile\\\",\\\"parentDataset\\\":\\\"\\\",\\\"publishFrequency\\\":\\\"irregular\\\",\\\"referenceUrls\\\":\\\"\\\",\\\"rights\\\":\\\"\\\",\\\"riskRating\\\":0,\\\"spatial\\\":\\\"Linden, Columbus, OH\\\",\\\"temporal\\\":\\\"\\\",\\\"__brook_struct__\\\":\\\"Elixir.SmartCity.Dataset.Business\\\"},\\\"id\\\":\\\"040ffb3b-29d3-440e-a0c8-c540ef5e8b49\\\",\\\"technical\\\":{\\\"allow_duplicates\\\":true,\\\"authBody\\\":{\\\"audience\\\":\\\"https://columbus-columbus-columbus-sitecc.us.fm.easymile.com/api/public/v3\\\",\\\"client_id\\\":\\\"<%= Reaper.SecretRetriever.retrieve_dataset_credentials(~s/easymile__linden/) |> elem(1) |> Map.get(~s/client_id/)  %>\\\",\\\"client_secret\\\":\\\"<%= Reaper.SecretRetriever.retrieve_dataset_credentials(~s/easymile__linden/) |> elem(1) |> Map.get(~s/client_secret/) %>\\\",\\\"grant_type\\\":\\\"client_credentials\\\"},\\\"authBodyEncodeMethod\\\":null,\\\"authHeaders\\\":{},\\\"authUrl\\\":\\\"https://easymile-sitecc.eu.auth0.com/oauth/token\\\",\\\"cadence\\\":\\\"*/2 * * * * *\\\",\\\"credentials\\\":false,\\\"dataName\\\":\\\"linden_positions\\\",\\\"orgId\\\":\\\"e3b6b6ec-d7e0-46ce-b859-1dbd0ed11bf8\\\",\\\"orgName\\\":\\\"easymile\\\",\\\"private\\\":false,\\\"protocol\\\":null,\\\"schema\\\":[{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"Type of feature. vehicle positions is the only possible entry.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"type\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"string\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"attributes of the CEAV positions\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"attributes\\\",\\\"pii\\\":\\\"None\\\",\\\"subSchema\\\":[{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"Identification of the CEAV.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"vehicle_id\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"string\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"theta\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"float\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"current speed of the CEAV.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"speed\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"float\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"Longitude of the CEAV.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"lon\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"float\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"Latitude of the CEAV.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"lat\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"float\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"timestamp when the vehicle position was last received.\\\",\\\"format\\\":\\\"{ISO:Extended:Z}\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"last_seen\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"timestamp\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"activity of the CEAV.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"activity\\\",\\\"pii\\\":\\\"None\\\",\\\"subSchema\\\":[{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"vehicle state. Metro and Idle are the possible values.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"type\\\",\\\"pii\\\":\\\"None\\\",\\\"type\\\":\\\"string\\\"},{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"progression of the CEAV.\\\",\\\"masked\\\":\\\"N/A\\\",\\\"name\\\":\\\"progression\\\",\\\"pii\\\":\\\"None\\\",\\\"subSchema\\\":[{\\\"biased\\\":\\\"No\\\",\\\"demographic\\\":\\\"None\\\",\\\"description\\\":\\\"CEAV stops along this route.\\\",\\\"itemType\\\":\\\"map\\\",\\\"mas" <> ..., :create, 1596054418003, []}, {:kafka_message, 39777688, "data:extract:start", "{\"__brook_struct__\":\"Elixir.Brook.Event\",\"__struct__\":\"Elixir.SmartCity.Dataset\",\"author\":\"reaper\",\"create_ts\":1596054418003,\"data\":\"{\\\"business\\\":{\\\"authorEmail\\\":null,\\\"authorName\\\":null,\\\"benefitRating\\\":1,\\\"categories\\\":null,\\\"conformsToUri\\\":\\\"https://project-open-data.cio.gov/v1.1/schema/\\\",\\\"contactEmail\\\":\\\"info@easymile.com\\\",\\\"contactName\\\":\\\"Easy Mile Inquiries\\\",\\\"dataTitle\\\":\\\"Easy Mile States - Linden Deployment\\\",\\\"describedByMimeType\\\":\\\"\\\",\\\"describedByUrl\\\":\\\"\\\",\\\"description\\\":\\\"This dataset presents the information about the CEAV vehicle states in the Linden Deployment.\\\",\\\"homepage\\\":\\\"https://columbus-columbus-columbus-sitecc.us.fm.easymile.com/api/public/v3\\\",\\\"issuedDate\\\":\\\"2020-02-05T00:00:00Z\\\",\\\"keywords\\\":[\\\"Autonomous\\\",\\\"Electric\\\",\\\"Shuttle\\\",\\\"First Mile Last Mile\\\"],\\\"language\\\":\\\"en-US\\\",\\\"license\\\":\\\"http://opendefinition.org/licenses/cc-by/\\\",\\\"modifiedDate\\\":\\\"2019-05-01T00:00:00Z\\\",\\\"orgTitle\\\":\\\"Easy Mile\\\",\\\"parentDataset\\\":\\\"\\\",\\\"publishFrequency\\\":\\\"irregular\\\",\\\"referenceUrls\\\":\\\"\\\",\\\"rights\\\":\\\"\\\",\\\"riskRating\\\":0,\\\"spatial\\\":\\\"Linden, Columbus, OH\\\",\\\"temporal\\\":\\\"\\\",\\\"__brook_struct__\\\":\\\"Elixir.SmartCity.Dataset.Business\\\"},\\\"id\\\":\\\"ffe10222-cd58-4618-a11c-7870a8169625\\\",\\\"technical\\\":{\\\"allow_duplicates\\\":true,\\\"authBody\\\":{\\\"audience\\\":\\\"https://columbus-columbus-columbus-sitecc.us.fm.easymile.com/api/public/v3\\\",\\\"client_id\\\":\\\"<%= Reaper.SecretRetriever.retrieve_dataset_creden (truncated)

**Expected behavior**
No errors about this event

**Comment by LtChae** [comment]
Closed. Not a bug, this is brook trying to update dataset indexes while that index is being built on startup. It fails until it is able to process the event.

The errors in the logs should be cleared up when we no longer rebuild the index each time the app starts.
