### ISSUE TITLE
Rest to SOAP Microservice

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#859]
As a data curator I would like to be able to ingest data into the platform from SOAP interfaces.

AC:
- [ ] Microservice exposes an endpoint that takes 3x parameters
   - WSDL URL
   - Action to invoke
   - map or list? of parameters to pass to action
- [ ] service then consumes the WSDL and dynamically invokes the action and returns the response it receives

TN:
- [ ] Do not need transform the data
- [ ] How do we handle errors?  For this card assume happy path but write card(s) for any edge cases identified while working this
- [ ] New Application
- [ ] Probably written in Java

https://examples.javacodegeeks.com/enterprise-java/jws/jax-ws-dynamic-proxy-client-example/

**Comment by JulieMaterni** [comment]
Card 1: CICD - 3pts

Card 2: Webservice - 5pts
