### ISSUE TITLE
Update ETL to use Meter & Zone Inventory from OS

### ISSUE THREAD

**Issue by JulieMaterni** [smartcitiesdata/smartcitiesdata#871]
Description: 
Do the minimum amount necessary to go from using the internal MZI table to the new MZI data source during the parking availability dataset ETL process.

https://discovery.smartcolumbusos.com/dataset/city_of_columbus/columbus_parking_meters

AC:
- [ ] Pull Meter & Zone Inventory data source from SCOS instead of internal table

**Comment by drmrd** [comment]
Description: Do the minimum amount necessary to go from using the internal MZI table to the new MZI data source during the parking availability dataset ETL process.
