### ISSUE TITLE
Automate geocoding the Meter & Zone Inventory

### ISSUE THREAD

**Issue by JulieMaterni** [smartcitiesdata/smartcitiesdata#872]
AC:
- [ ] The PredictiveParking ETL process should result in a table wherein every record has an associated geometry column (or columns) describing the location of the parking zone (in WKT format, as longlats/latlongs, as individual lat and long columns, as a geohash, or in whichever common geometry format is most convenient to the author).
- [ ] If zones are given in the MZI with addresses but not latlongs/other geometric info, their addresses should be geocoded to obtain coordinates in a convenient format.
- [ ] For the purposes of this card, these geometries don't have to be super accurate. For instance …
- for zones given a single point location in the MZI, this point can used for the geometry in the output of the ETL process, and
- for zones comprised of parking meters, the centroid of the coordinates of all the zone's parking meters can be used.
(If zones exist containing both metered and meter-less regions, talk to @drmrd for a solution.)

Notes:
- These will probably use per zone lat/longs.
- Need to review data in more detail.
- This is not part of the v2 E2E MVP for PredictiveParking and should be considered a nice-to-have for the time being.

**Comment by drmrd** [comment]
ACs:
- [ ] The PredictiveParking ETL process should result in a table wherein every record has an associated geometry column (or columns) describing the location of the parking zone (in WKT format, as longlats/latlongs, as individual lat and long columns, as a geohash, or in whichever common geometry format is most convenient to the author).
- [ ] If zones are given in the MZI with addresses but not latlongs/other geometric info, their addresses should be geocoded to obtain coordinates in a convenient format.
- [ ] For the purposes of this card, these geometries don't have to be super accurate. For instance …
  - for zones given a single point location in the MZI, this point can used for the geometry in the output of the ETL process, and
  - for zones comprised of parking meters, the centroid of the coordinates of all the zone's parking meters can be used.
  (If zones exist containing both metered and meter-less regions, talk to @drmrd for a solution.)

Notes:
- This is not part of the v2 E2E MVP for PredictiveParking and should be considered a nice-to-have for the time being.
