### ISSUE TITLE
Have parking model cluster during training

### ISSUE THREAD

**Issue by JulieMaterni** [smartcitiesdata/smartcitiesdata#873]
Further clustering is an implementation detail of the parking availability model. Our workflow should reflect this.

AC:
- [x]  Create parking zone clusters at training time.
- [x]  Store zone-to-cluster map as part of each trained model artifact.
- [x]  Add deprecation warning to zone_info public functions.

**Comment by drmrd** [comment]
ACs:
- [ ] Create parking zone clusters at training time.
- [ ] Store zone-to-cluster map as part of each trained model artifact.
- [ ] Add deprecation warning to `zone_info` public functions.
