### ISSUE TITLE
Simplify ETL to remove IPS- and PM-specific tables

### ISSUE THREAD

**Issue by JulieMaterni** [smartcitiesdata/smartcitiesdata#875]
AC:
- [ ] Consolidate the IPS- and ParkMobile-specific SQL queries

Notes:
- Not one of the required cards for v2 of the PredictiveParking data pipeline but would simplify the current ETL process significantly.

**Comment by drmrd** [comment]
ACs:
- [ ] Consolidate the IPS- and ParkMobile-specific SQL queries

Notes:
- Not one of the required cards for v2 of the PredictiveParking data pipeline but would simplify the current ETL process significantly.

Blocked by:
- MZI data source creation card
- Card to incorporate MZI data source into current ETL
