### ISSUE TITLE
SPIKE: How can the curator review a sample of the data to evaluate for PII? 

### ISSUE THREAD

**Issue by JulieMaterni** [smartcitiesdata/smartcitiesdata#905]
As a data curator, I want to review a sample of the submitted data so that I can evaluate for PII before approving or rejecting for ingestion into the OS. Our current approach has been that providers will email a sample of the data to Ram/Anthoni for review.

ACs: 
- [ ] Partner with Warner to determine options for providing a data sample to the curator for review
- [ ] Create cards for selected approach

**Comment by warnerAWESOMEmoore** [comment]
Assumption is that PII collection is out of scope. These recommendations are meant to reduce the likelihood of PII being introduced and control the risk if it is.

Initial thoughts:

- Isolated environment or avoid collecting data (IE. link to external source to validate)
- Notice at point of collection not to submit PII
- Input validation and rejection if PII is submitted (SSN, DOB, name, PHI, credit card(s))
- Limited retention and secure deletion for submitted data
- Encryption in transit and at rest
- Require MFA to access any area that contains pre-curated data
- Detailed logging

**Comment by warnerAWESOMEmoore** [comment]
Dan Moore identified Presidio as a possible solution for the input validation: https://github.com/microsoft/presidio
